#!/usr/bin/env bash
# One-time setup for the SDLC loop: the steps only a person can do, one at a
# time, with a check after each. Secrets are typed into `gh secret set`
# directly; they never appear in a file, an argument, or an agent transcript.
set -euo pipefail

repo="$(gh repo view --json nameWithOwner -q .nameWithOwner)"
echo "SDLC loop bootstrap for $repo"
echo

step() { printf '\n== %s ==\n' "$1"; }
ask() { local a; read -r -p "$1 [y/N] " a; [[ "${a:-N}" =~ ^[Yy]$ ]]; }
have_secret() { gh secret list | awk '{print $1}' | grep -qx "$1"; }

step "1/5 Model credential (one of two)"
cat <<'EOF'
The CI-run stages (spec, plan, build, review, diagnose, evals) run `claude -p`
on a runner and need ONE of these repository secrets:
  a) CLAUDE_CODE_OAUTH_TOKEN  Pro/Max subscription. Run `claude setup-token`
                              on this machine and paste the token it prints.
                              No API billing; uses the subscription's limits.
  b) ANTHROPIC_API_KEY        API billing per token, from console.anthropic.com.
Local work (hooks, npm run verify, receipts) needs neither.
EOF
if have_secret CLAUDE_CODE_OAUTH_TOKEN || have_secret ANTHROPIC_API_KEY; then
  echo "present: $(have_secret CLAUDE_CODE_OAUTH_TOKEN && echo CLAUDE_CODE_OAUTH_TOKEN) $(have_secret ANTHROPIC_API_KEY && echo ANTHROPIC_API_KEY)"
  ask "Rotate or add one now?" && { read -r -p "Which? [oauth/api] " which; [ "$which" = api ] && gh secret set ANTHROPIC_API_KEY || gh secret set CLAUDE_CODE_OAUTH_TOKEN; }
else
  echo "missing. gh will prompt for the value; nothing is echoed."
  read -r -p "Set which? [oauth/api/skip] " which
  case "$which" in api) gh secret set ANTHROPIC_API_KEY;; oauth) gh secret set CLAUDE_CODE_OAUTH_TOKEN;; *) echo "skipped";; esac
fi
{ have_secret CLAUDE_CODE_OAUTH_TOKEN || have_secret ANTHROPIC_API_KEY; } && echo "check: a model credential is present" || echo "check: STILL MISSING"

step "2/5 SDLC_GITHUB_TOKEN repository secret (fine-grained PAT)"
cat <<'EOF'
Why: pull requests and pushes made with the workflow's own GITHUB_TOKEN do not
trigger other workflows, so a PR the loop opens would never get CI and could
never satisfy branch protection. The loop pushes and opens PRs with this token
instead.
Create it at https://github.com/settings/personal-access-tokens/new
  Repository access: only this repository
  Permissions: Contents (read and write), Pull requests (read and write),
               Issues (read and write), Workflows (read and write)
  Expiration: what your policy allows; rotate through this script.
EOF
if have_secret SDLC_GITHUB_TOKEN; then
  echo "present."
  ask "Rotate it now?" && gh secret set SDLC_GITHUB_TOKEN
else
  ask "Set it now?" && gh secret set SDLC_GITHUB_TOKEN
fi
have_secret SDLC_GITHUB_TOKEN && echo "check: present" || echo "check: STILL MISSING"

step "3/5 Branch protection on main (every CI job required incl. SDLC verify, no direct pushes, admins included; 0 approvals because a single maintainer cannot approve their own PR — the review workflow and the merge are the acceptance)"
if gh api "repos/$repo/branches/main/protection" >/dev/null 2>&1; then
  echo "present:"; gh api "repos/$repo/branches/main/protection" -q '{checks: .required_status_checks.contexts, reviews: .required_pull_request_reviews.required_approving_review_count, admins: .enforce_admins.enabled}'
else
  echo "missing. This is what makes 'agents act up to the gate and not past it' a property of the repo."
  if ask "Apply now (requires admin on the repo)?"; then
    gh api -X PUT "repos/$repo/branches/main/protection" --input - <<'JSON'
{
  "required_status_checks": { "strict": true, "contexts": ["Analyze (javascript-typescript)", "CodeQL", "Build & Test (macos-latest, Node 22)", "Build & Test (macos-latest, Node 24)", "Build & Test (ubuntu-latest, Node 22)", "Build & Test (ubuntu-latest, Node 24)", "Build & Test (ubuntu-latest, Node 26)", "Build & Test (windows-latest, Node 22)", "Build & Test (windows-latest, Node 24)", "Coverage floor", "Packaged Artifact Smoke Test", "Packaged Dashboard E2E Smoke", "Release Verification Gate", "SDLC verify"] },
  "enforce_admins": true,
  "required_pull_request_reviews": { "required_approving_review_count": 0, "dismiss_stale_reviews": true },
  "restrictions": null,
  "allow_force_pushes": false,
  "allow_deletions": false
}
JSON
    echo "check:"; gh api "repos/$repo/branches/main/protection" -q '{checks: .required_status_checks.contexts, reviews: .required_pull_request_reviews.required_approving_review_count, admins: .enforce_admins.enabled}'
  fi
fi

step "4/5 Labels the loop uses"
for pair in "sdlc:spec|Spec generated by the loop; merge with status accepted to start the plan|0f6e74" \
            "sdlc:plan|Plan generated by the loop; merge with status accepted to start the build|0f6e74" \
            "sdlc:build|Implementation opened by the loop; review per REVIEW.md|a15c0a" \
            "sdlc:intent|Intent filed by the monitor; triage it|a15c0a" \
            "sdlc:release|Post-deploy release receipt|2f6b3a" \
            "sdlc:breach|Control band breached; one open issue per metric|a63d40"; do
  IFS='|' read -r name desc color <<<"$pair"
  if gh label list --json name -q '.[].name' | grep -qx "$name"; then echo "have $name"; else gh label create "$name" --description "$desc" --color "$color" && echo "created $name"; fi
done

step "5/5 Try the loop without spending anything"
echo "  node scripts/sdlc/next-stage.mjs --human        # what is accepted and waiting"
echo "  node scripts/sdlc/run-stage.mjs --stage spec --slug <slug> --artifact intent/<slug>.md --dry-run"
echo "  npm run verify                                     # the definition of done"
echo
echo "Then write intent/<slug>.md from intent/TEMPLATE.md, merge it with status: accepted, and watch Actions → SDLC loop."
